### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by andrewjaykeller** [openexp/OpenEXP#20]
Running an `npm install --all` i was met with a need for at least two dependencies and possibly a third:
1. kerberos
    \* solved with `npm install kerberos`
2. webpack
    \* solved with `npm install web pack`
3. regexpu
    \* went away, not sure if solved

**Comment by tashoecraft** [comment]
you shouldn't be running npm init, that is only for when you are first creating a package.json in a new file. Clear the project, and try repulling and only npm installing.

**Comment by andrewjaykeller** [comment]
Whoops, i meant to write `npm install --all` edited my issue.

**Comment by tashoecraft** [comment]
you shouldn't need the all tag, but I'll try and replicate and see if it is an issue

**Comment by tashoecraft** [comment]
I recloned into a new directory and didn't get the issue. Can you try to reclone and see if you just do, npm install, then npm run build if any issues pop up? And post a screen shot of any errors, the github text boxes accept pictures dragged in.

**Comment by andrewjaykeller** [comment]
the error did not persist while cloning into a new dir... it worked with no errors, maybe you should reformat your computer and try to do it again

**Comment by tashoecraft** [comment]
burden of proof is on the prosecutor

**Comment by tashoecraft** [comment]
I'm going to close this issue unless it can be redone, then we can open it back up

**Comment by andrewjaykeller** [comment]
ok
