### ISSUE TITLE
ADD spin animation on startup

### ISSUE THREAD

**Issue by andrewheusser** [openexp/OpenEXP#22]
Slack has a nice little animation while things are loading initially.  It would look nice to add something like this eventually, not a priority though

**Comment by andrewjaykeller** [comment]
could use the gif that open BCI has for the mark IV... http://openbci.com that front one

**Comment by tashoecraft** [comment]
That's a little long, and startup time is variable. Inspirational quotes?

**Comment by andrewjaykeller** [comment]
all you need to do is put it on like a 3 second timer, even if it only takes one second to actually initialize, the user get's used to watching this 3 second load gif and even as we add more functionality, user never notices...

**Comment by andrewheusser** [comment]
i feel like that might be a little complex, i'm thinking clean and simple, like the slack load animation.  ill take a look at some of the css3 animations.  angular also has animation options, correct?

**Comment by tashoecraft** [comment]
angular has ngAnimate, but css is all you really need here.
