### ISSUE TITLE
ADD calibration requirement prior to running experiment

### ISSUE THREAD

**Issue by andrewheusser** [openexp/OpenEXP#24]
In order to make sure users are collecting clean data, a series of semi automated calibrations should be performed.  These tests should include:

1) testing for solid connection at each electrode 

2) checking impedance on each connection and recording this

3) test trigger latencies 

more?

**Comment by teonbrooks** [comment]
impedance testing is being worked on here: https://github.com/OpenBCI/openbci-js-sdk/issues/29
trigger latency

**Comment by andrewjaykeller** [comment]
God I'm trying :(

AJ Keller
Founder 
Push The World
843-471-0039

On Fri, Feb 26, 2016 at 3:26 PM -0800, "Teon L Brooks" notifications@github.com wrote:

impedence testing is being worked on here: OpenBCI/openbci-js-sdk#29

trigger latency

**Comment by teonbrooks** [comment]
@pushtheworldllc we have faith in you AJ! let me know if I can do anything help. will close for your pr
