### ISSUE TITLE
connect with factorsDB

### ISSUE THREAD

**Issue by andrewheusser** [openexp/OpenEXP#25]
Connect the app with factorsdb.org database: http://www.factorsdb.org/
This will serve as a repository for experiments.

https://github.com/jodeleeuw/factorsdb

**Comment by andrewheusser** [comment]
one issue with using this database is that the experiments will not have triggers implemented.. ill have to touch base with @jodeleeuw on this

**Comment by andrewjaykeller** [comment]
I am going to need to connect my app to a db as well, so i will pay close attention here!
