### ISSUE TITLE
issue with localhost:8080 reference

### ISSUE THREAD

**Issue by andrewheusser** [openexp/OpenEXP#42]
```
<script src="http://localhost:8080/webpack-dev-server.js"></script>
<script src="http://localhost:8080/build/vendor.js"></script>
<script src="http://localhost:8080/build/app.js"></script>
```

this doesn't seem to work for me, but it works when i change it to:

```
    <script src="./webpack-dev-server.js"></script>
    <script src="./build/vendor.js"></script>
    <script src="./build/app.js"></script>
```

the vendor and app work, but webpack-dev-server still does not. any ideas?

**Comment by tashoecraft** [comment]
Can you post a screenshot of the error you are getting? In order to get the auto building, it has to be linked to the dev server and not statically linked. The second one works because you have a already built version, so you are linking to a bunch of built assets. The server works for me on master.

**Comment by tashoecraft** [comment]
![screen shot 2015-12-29 at 7 15 48 pm](https://cloud.githubusercontent.com/assets/10655908/12044516/98636274-ae60-11e5-9754-20a020804655.png)
were you getting this?

**Comment by andrewheusser** [comment]
<img width="1202" alt="screen shot 2015-12-29 at 8 47 07 pm" src="https://cloud.githubusercontent.com/assets/6596567/12045227/63e69b08-ae6d-11e5-80b0-223043effec9.png">

**Comment by andrewheusser** [comment]
Figured out what was going on.  I was running `npm run build` instead of `npm run watch`

It works when I run `npm run watch` and then in a separate terminal window `npm start electron`
