### ISSUE TITLE
webpack => gulp refactor

### ISSUE THREAD

**Issue by tashoecraft** [openexp/OpenEXP#53]
Web pack seems to be causing more problems then it is worth (hot-reloading and bundling) so I think we should move over to a gulp build process. With electron we can use require() on the front end, as there isn't a really separation. It will mostly look the same, except the build process will be a little different (down to one command hopefully).

**Comment by andrewjaykeller** [comment]
+1

**Comment by andrewheusser** [comment]
@tashoecraft, is this resolved now?  we are going to use webpack right?

**Comment by andrewjaykeller** [comment]
can we close this?
